//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.23 at 10:57:51 AM CEST 
//


package org.cxml.v12028;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "unitGrossPrice",
    "informationalPrice",
    "informationalPriceExclTax",
    "unitNetPriceCorrection"
})
@XmlRootElement(name = "AdditionalPrices")
public class AdditionalPrices {

    @XmlElement(name = "UnitGrossPrice")
    protected UnitGrossPrice unitGrossPrice;
    @XmlElement(name = "InformationalPrice")
    protected InformationalPrice informationalPrice;
    @XmlElement(name = "InformationalPriceExclTax")
    protected InformationalPriceExclTax informationalPriceExclTax;
    @XmlElement(name = "UnitNetPriceCorrection")
    protected UnitNetPriceCorrection unitNetPriceCorrection;

    /**
     * Gets the value of the unitGrossPrice property.
     * 
     * @return
     *     possible object is
     *     {@link UnitGrossPrice }
     *     
     */
    public UnitGrossPrice getUnitGrossPrice() {
        return unitGrossPrice;
    }

    /**
     * Sets the value of the unitGrossPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitGrossPrice }
     *     
     */
    public void setUnitGrossPrice(UnitGrossPrice value) {
        this.unitGrossPrice = value;
    }

    /**
     * Gets the value of the informationalPrice property.
     * 
     * @return
     *     possible object is
     *     {@link InformationalPrice }
     *     
     */
    public InformationalPrice getInformationalPrice() {
        return informationalPrice;
    }

    /**
     * Sets the value of the informationalPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link InformationalPrice }
     *     
     */
    public void setInformationalPrice(InformationalPrice value) {
        this.informationalPrice = value;
    }

    /**
     * Gets the value of the informationalPriceExclTax property.
     * 
     * @return
     *     possible object is
     *     {@link InformationalPriceExclTax }
     *     
     */
    public InformationalPriceExclTax getInformationalPriceExclTax() {
        return informationalPriceExclTax;
    }

    /**
     * Sets the value of the informationalPriceExclTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link InformationalPriceExclTax }
     *     
     */
    public void setInformationalPriceExclTax(InformationalPriceExclTax value) {
        this.informationalPriceExclTax = value;
    }

    /**
     * Gets the value of the unitNetPriceCorrection property.
     * 
     * @return
     *     possible object is
     *     {@link UnitNetPriceCorrection }
     *     
     */
    public UnitNetPriceCorrection getUnitNetPriceCorrection() {
        return unitNetPriceCorrection;
    }

    /**
     * Sets the value of the unitNetPriceCorrection property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitNetPriceCorrection }
     *     
     */
    public void setUnitNetPriceCorrection(UnitNetPriceCorrection value) {
        this.unitNetPriceCorrection = value;
    }

}
