//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.23 at 10:57:51 AM CEST 
//


package org.cxml.v12028;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "invoiceDetailRequestHeader",
    "invoiceDetailOrderOrInvoiceDetailHeaderOrder",
    "invoiceDetailSummary"
})
@XmlRootElement(name = "InvoiceDetailRequest")
public class InvoiceDetailRequest {

    @XmlElement(name = "InvoiceDetailRequestHeader", required = true)
    protected InvoiceDetailRequestHeader invoiceDetailRequestHeader;
    @XmlElements({
        @XmlElement(name = "InvoiceDetailOrder", required = true, type = InvoiceDetailOrder.class),
        @XmlElement(name = "InvoiceDetailHeaderOrder", required = true, type = InvoiceDetailHeaderOrder.class)
    })
    protected List<Object> invoiceDetailOrderOrInvoiceDetailHeaderOrder;
    @XmlElement(name = "InvoiceDetailSummary", required = true)
    protected InvoiceDetailSummary invoiceDetailSummary;

    /**
     * Gets the value of the invoiceDetailRequestHeader property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceDetailRequestHeader }
     *     
     */
    public InvoiceDetailRequestHeader getInvoiceDetailRequestHeader() {
        return invoiceDetailRequestHeader;
    }

    /**
     * Sets the value of the invoiceDetailRequestHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceDetailRequestHeader }
     *     
     */
    public void setInvoiceDetailRequestHeader(InvoiceDetailRequestHeader value) {
        this.invoiceDetailRequestHeader = value;
    }

    /**
     * Gets the value of the invoiceDetailOrderOrInvoiceDetailHeaderOrder property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the invoiceDetailOrderOrInvoiceDetailHeaderOrder property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInvoiceDetailOrderOrInvoiceDetailHeaderOrder().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InvoiceDetailOrder }
     * {@link InvoiceDetailHeaderOrder }
     * 
     * 
     */
    public List<Object> getInvoiceDetailOrderOrInvoiceDetailHeaderOrder() {
        if (invoiceDetailOrderOrInvoiceDetailHeaderOrder == null) {
            invoiceDetailOrderOrInvoiceDetailHeaderOrder = new ArrayList<Object>();
        }
        return this.invoiceDetailOrderOrInvoiceDetailHeaderOrder;
    }

    /**
     * Gets the value of the invoiceDetailSummary property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceDetailSummary }
     *     
     */
    public InvoiceDetailSummary getInvoiceDetailSummary() {
        return invoiceDetailSummary;
    }

    /**
     * Sets the value of the invoiceDetailSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceDetailSummary }
     *     
     */
    public void setInvoiceDetailSummary(InvoiceDetailSummary value) {
        this.invoiceDetailSummary = value;
    }

}
