//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.06 at 12:54:05 AM EDT 
//


package org.cxml.invoicedetail;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "timeCardReferenceOrTimeCardIDInfo"
})
@XmlRootElement(name = "InvoiceTimeCardDetail")
public class InvoiceTimeCardDetail {

    @XmlElements({
        @XmlElement(name = "TimeCardReference", required = true, type = TimeCardReference.class),
        @XmlElement(name = "TimeCardIDInfo", required = true, type = TimeCardIDInfo.class)
    })
    protected List<Object> timeCardReferenceOrTimeCardIDInfo;

    /**
     * Gets the value of the timeCardReferenceOrTimeCardIDInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the timeCardReferenceOrTimeCardIDInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTimeCardReferenceOrTimeCardIDInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TimeCardReference }
     * {@link TimeCardIDInfo }
     * 
     * 
     */
    public List<Object> getTimeCardReferenceOrTimeCardIDInfo() {
        if (timeCardReferenceOrTimeCardIDInfo == null) {
            timeCardReferenceOrTimeCardIDInfo = new ArrayList<Object>();
        }
        return this.timeCardReferenceOrTimeCardIDInfo;
    }

}
