//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.06 at 12:54:05 AM EDT 
//


package org.cxml.invoicedetail;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "orderReferenceOrMasterAgreementReferenceOrMasterAgreementIDInfoOrSupplierOrderInfoOrOrderIDInfo"
})
@XmlRootElement(name = "InvoiceDetailOrderInfo")
public class InvoiceDetailOrderInfo {

    @XmlElements({
        @XmlElement(name = "OrderReference", required = true, type = OrderReference.class),
        @XmlElement(name = "MasterAgreementReference", required = true, type = MasterAgreementReference.class),
        @XmlElement(name = "MasterAgreementIDInfo", required = true, type = MasterAgreementIDInfo.class),
        @XmlElement(name = "SupplierOrderInfo", required = true, type = SupplierOrderInfo.class),
        @XmlElement(name = "OrderIDInfo", required = true, type = OrderIDInfo.class)
    })
    protected List<Object> orderReferenceOrMasterAgreementReferenceOrMasterAgreementIDInfoOrSupplierOrderInfoOrOrderIDInfo;

    /**
     * Gets the value of the orderReferenceOrMasterAgreementReferenceOrMasterAgreementIDInfoOrSupplierOrderInfoOrOrderIDInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderReferenceOrMasterAgreementReferenceOrMasterAgreementIDInfoOrSupplierOrderInfoOrOrderIDInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderReferenceOrMasterAgreementReferenceOrMasterAgreementIDInfoOrSupplierOrderInfoOrOrderIDInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrderReference }
     * {@link MasterAgreementReference }
     * {@link MasterAgreementIDInfo }
     * {@link SupplierOrderInfo }
     * {@link OrderIDInfo }
     * 
     * 
     */
    public List<Object> getOrderReferenceOrMasterAgreementReferenceOrMasterAgreementIDInfoOrSupplierOrderInfoOrOrderIDInfo() {
        if (orderReferenceOrMasterAgreementReferenceOrMasterAgreementIDInfoOrSupplierOrderInfoOrOrderIDInfo == null) {
            orderReferenceOrMasterAgreementReferenceOrMasterAgreementIDInfoOrSupplierOrderInfoOrOrderIDInfo = new ArrayList<Object>();
        }
        return this.orderReferenceOrMasterAgreementReferenceOrMasterAgreementIDInfoOrSupplierOrderInfoOrOrderIDInfo;
    }

}
