//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.23 at 11:18:10 AM CEST 
//


package org.cxml.fulfill;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "discountPercentOrDiscountAmount"
})
@XmlRootElement(name = "Discount")
public class Discount {

    @XmlElements({
        @XmlElement(name = "DiscountPercent", required = true, type = DiscountPercent.class),
        @XmlElement(name = "DiscountAmount", required = true, type = DiscountAmount.class)
    })
    protected List<Object> discountPercentOrDiscountAmount;

    /**
     * Gets the value of the discountPercentOrDiscountAmount property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the discountPercentOrDiscountAmount property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDiscountPercentOrDiscountAmount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DiscountPercent }
     * {@link DiscountAmount }
     * 
     * 
     */
    public List<Object> getDiscountPercentOrDiscountAmount() {
        if (discountPercentOrDiscountAmount == null) {
            discountPercentOrDiscountAmount = new ArrayList<Object>();
        }
        return this.discountPercentOrDiscountAmount;
    }

}
