//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.23 at 11:18:10 AM CEST 
//


package org.cxml.fulfill;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "receiptRequestHeader",
    "receiptOrder",
    "total"
})
@XmlRootElement(name = "ReceiptRequest")
public class ReceiptRequest {

    @XmlElement(name = "ReceiptRequestHeader", required = true)
    protected ReceiptRequestHeader receiptRequestHeader;
    @XmlElement(name = "ReceiptOrder", required = true)
    protected List<ReceiptOrder> receiptOrder;
    @XmlElement(name = "Total", required = true)
    protected Total total;

    /**
     * Gets the value of the receiptRequestHeader property.
     * 
     * @return
     *     possible object is
     *     {@link ReceiptRequestHeader }
     *     
     */
    public ReceiptRequestHeader getReceiptRequestHeader() {
        return receiptRequestHeader;
    }

    /**
     * Sets the value of the receiptRequestHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReceiptRequestHeader }
     *     
     */
    public void setReceiptRequestHeader(ReceiptRequestHeader value) {
        this.receiptRequestHeader = value;
    }

    /**
     * Gets the value of the receiptOrder property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the receiptOrder property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReceiptOrder().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReceiptOrder }
     * 
     * 
     */
    public List<ReceiptOrder> getReceiptOrder() {
        if (receiptOrder == null) {
            receiptOrder = new ArrayList<ReceiptOrder>();
        }
        return this.receiptOrder;
    }

    /**
     * Gets the value of the total property.
     * 
     * @return
     *     possible object is
     *     {@link Total }
     *     
     */
    public Total getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     * @param value
     *     allowed object is
     *     {@link Total }
     *     
     */
    public void setTotal(Total value) {
        this.total = value;
    }

}
