//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.23 at 11:18:10 AM CEST 
//


package org.cxml.fulfill;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "partnerContact",
    "documentReferenceOrDocumentInfo",
    "serviceEntryDetailLineIndicator",
    "serviceEntryDetailShipping",
    "shipNoticeIDInfo",
    "paymentTerm",
    "period",
    "comments",
    "extrinsic"
})
@XmlRootElement(name = "ServiceEntryRequestHeader")
public class ServiceEntryRequestHeader {

    @XmlAttribute(name = "serviceEntryDate", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String serviceEntryDate;
    @XmlAttribute(name = "serviceEntryID", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String serviceEntryID;
    @XmlAttribute(name = "supplierReferenceNumber")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String supplierReferenceNumber;
    @XmlAttribute(name = "operation")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String operation;
    @XmlElement(name = "PartnerContact")
    protected List<PartnerContact> partnerContact;
    @XmlElements({
        @XmlElement(name = "DocumentReference", type = DocumentReference.class),
        @XmlElement(name = "DocumentInfo", type = DocumentInfo.class)
    })
    protected List<Object> documentReferenceOrDocumentInfo;
    @XmlElement(name = "ServiceEntryDetailLineIndicator")
    protected ServiceEntryDetailLineIndicator serviceEntryDetailLineIndicator;
    @XmlElement(name = "ServiceEntryDetailShipping")
    protected ServiceEntryDetailShipping serviceEntryDetailShipping;
    @XmlElement(name = "ShipNoticeIDInfo")
    protected ShipNoticeIDInfo shipNoticeIDInfo;
    @XmlElement(name = "PaymentTerm")
    protected List<PaymentTerm> paymentTerm;
    @XmlElement(name = "Period")
    protected Period period;
    @XmlElement(name = "Comments")
    protected Comments comments;
    @XmlElement(name = "Extrinsic")
    protected List<Extrinsic> extrinsic;

    /**
     * Gets the value of the serviceEntryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceEntryDate() {
        return serviceEntryDate;
    }

    /**
     * Sets the value of the serviceEntryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceEntryDate(String value) {
        this.serviceEntryDate = value;
    }

    /**
     * Gets the value of the serviceEntryID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceEntryID() {
        return serviceEntryID;
    }

    /**
     * Sets the value of the serviceEntryID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceEntryID(String value) {
        this.serviceEntryID = value;
    }

    /**
     * Gets the value of the supplierReferenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierReferenceNumber() {
        return supplierReferenceNumber;
    }

    /**
     * Sets the value of the supplierReferenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierReferenceNumber(String value) {
        this.supplierReferenceNumber = value;
    }

    /**
     * Gets the value of the operation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperation() {
        if (operation == null) {
            return "new";
        } else {
            return operation;
        }
    }

    /**
     * Sets the value of the operation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperation(String value) {
        this.operation = value;
    }

    /**
     * Gets the value of the partnerContact property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partnerContact property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartnerContact().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartnerContact }
     * 
     * 
     */
    public List<PartnerContact> getPartnerContact() {
        if (partnerContact == null) {
            partnerContact = new ArrayList<PartnerContact>();
        }
        return this.partnerContact;
    }

    /**
     * Gets the value of the documentReferenceOrDocumentInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentReferenceOrDocumentInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentReferenceOrDocumentInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocumentReference }
     * {@link DocumentInfo }
     * 
     * 
     */
    public List<Object> getDocumentReferenceOrDocumentInfo() {
        if (documentReferenceOrDocumentInfo == null) {
            documentReferenceOrDocumentInfo = new ArrayList<Object>();
        }
        return this.documentReferenceOrDocumentInfo;
    }

    /**
     * Gets the value of the serviceEntryDetailLineIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceEntryDetailLineIndicator }
     *     
     */
    public ServiceEntryDetailLineIndicator getServiceEntryDetailLineIndicator() {
        return serviceEntryDetailLineIndicator;
    }

    /**
     * Sets the value of the serviceEntryDetailLineIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceEntryDetailLineIndicator }
     *     
     */
    public void setServiceEntryDetailLineIndicator(ServiceEntryDetailLineIndicator value) {
        this.serviceEntryDetailLineIndicator = value;
    }

    /**
     * Gets the value of the serviceEntryDetailShipping property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceEntryDetailShipping }
     *     
     */
    public ServiceEntryDetailShipping getServiceEntryDetailShipping() {
        return serviceEntryDetailShipping;
    }

    /**
     * Sets the value of the serviceEntryDetailShipping property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceEntryDetailShipping }
     *     
     */
    public void setServiceEntryDetailShipping(ServiceEntryDetailShipping value) {
        this.serviceEntryDetailShipping = value;
    }

    /**
     * Gets the value of the shipNoticeIDInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ShipNoticeIDInfo }
     *     
     */
    public ShipNoticeIDInfo getShipNoticeIDInfo() {
        return shipNoticeIDInfo;
    }

    /**
     * Sets the value of the shipNoticeIDInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipNoticeIDInfo }
     *     
     */
    public void setShipNoticeIDInfo(ShipNoticeIDInfo value) {
        this.shipNoticeIDInfo = value;
    }

    /**
     * Gets the value of the paymentTerm property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paymentTerm property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPaymentTerm().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PaymentTerm }
     * 
     * 
     */
    public List<PaymentTerm> getPaymentTerm() {
        if (paymentTerm == null) {
            paymentTerm = new ArrayList<PaymentTerm>();
        }
        return this.paymentTerm;
    }

    /**
     * Gets the value of the period property.
     * 
     * @return
     *     possible object is
     *     {@link Period }
     *     
     */
    public Period getPeriod() {
        return period;
    }

    /**
     * Sets the value of the period property.
     * 
     * @param value
     *     allowed object is
     *     {@link Period }
     *     
     */
    public void setPeriod(Period value) {
        this.period = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link Comments }
     *     
     */
    public Comments getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Comments }
     *     
     */
    public void setComments(Comments value) {
        this.comments = value;
    }

    /**
     * Gets the value of the extrinsic property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extrinsic property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtrinsic().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Extrinsic }
     * 
     * 
     */
    public List<Extrinsic> getExtrinsic() {
        if (extrinsic == null) {
            extrinsic = new ArrayList<Extrinsic>();
        }
        return this.extrinsic;
    }

}
