//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.23 at 11:18:10 AM CEST 
//


package org.cxml.fulfill;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "shipNoticeItemRetail"
})
@XmlRootElement(name = "ShipNoticeItemIndustry")
public class ShipNoticeItemIndustry {

    @XmlElement(name = "ShipNoticeItemRetail")
    protected ShipNoticeItemRetail shipNoticeItemRetail;

    /**
     * Gets the value of the shipNoticeItemRetail property.
     * 
     * @return
     *     possible object is
     *     {@link ShipNoticeItemRetail }
     *     
     */
    public ShipNoticeItemRetail getShipNoticeItemRetail() {
        return shipNoticeItemRetail;
    }

    /**
     * Sets the value of the shipNoticeItemRetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipNoticeItemRetail }
     *     
     */
    public void setShipNoticeItemRetail(ShipNoticeItemRetail value) {
        this.shipNoticeItemRetail = value;
    }

}
